# FAST-LIO2 配置文件 for Livox MID-360

# 激光雷达类型
preprocess/lidar_type: 7  # 7代表Livox自定义PointCloud2类型

# 点云话题
common/lid_topic: "/livox/lidar"

# IMU话题（如有IMU，否则可留空或注释）
common/imu_topic: "/livox/imu"
imu/imu_en: true

# 激光雷达外参（如有标定结果请填写，否则保持默认）
extrinsic_T: [1, 0, 0, 0,
              0, 1, 0, 0,
              0, 0, 1, 0,
              0, 0, 0, 1]

# 激光雷达到IMU的旋转（如有IMU且已标定，否则保持默认）
extrinsic_R: [1, 0, 0,
              0, 1, 0,
              0, 0, 1]
extrinsic_T_imu: [0, 0, 0]

# 地图分辨率
map_resolution: 0.2

# 最大激光帧数
max_num_pts: 200000

# 是否保存地图
save_map: false

# MID-360 激光雷达参数
N_SCANS: 4  # MID-360 有 4 条扫描线
point_filter_num: 1  # 点云降采样率
blind: 0.01  # 盲区距离

# 禁用相机功能
use_camera: false

# 其他参数可根据实际需求调整 
common/img_en: 0 